services:
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: "host.docker.internal:9092"
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
